server:
  port: 8000

spring:
  application:
    name: apache-kafka-payment-api
  # Kafka Configuration
  kafka:
    producer:
      bootstrap-servers: localhost:29092
    consumer:
      bootstrap-servers: localhost:29092

kafka:
  topic:
    payment:
      name: payment-topic