server:
  port: ${PORT:8000}

spring:
  application:
    name: apache-kafka-payment-api
  # Kafka Configuration
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:29092}

kafka:
  topic:
    payment:
      name: payment-topic